let a=[0,9,6,77,2,3,21]
// console.log(a)
a.push(8)
a.push(5)
a.push(55)
a.push(8)
a.pop()
// console.log(a)
 a.unshift(90)
// console.log(a)
a.unshift(0)
a.shift()
// console.log(a)
// console.log(a.includes(90))
// console.log(a.indexOf(80))
// console.log(a.indexOf(5))
let b=a.join();
console.log(a)
console.log(b)